### ISSUE TITLE
Research AWS Services

### ISSUE THREAD

**Issue by JonathanWong592** [sean-hale-dev/resume-org#23]

**Comment by litala123** [comment]
The Lightsail service lets you run a virtual private server for a web app.

Lightsail service includes:
- Static IP address
- Intuitive management console
- DNS management
- 1-click SSH terminal access (Linux/Unix)
- 1-click RDP access (Windows)
- Powerful API
- Highly available SSD storage
- Server monitoring

Starts at $3.50/month with Linux servers, probably will be around that in production unless Windows servers are used (more expensive)

The $3.50/month model gives:
- 512 MB Memory
- 1 Core Processor
- 20 GB SSD Disk
- 1 TB Transfer

The $5.00/month model gives:
- 1 GB Memory
- 1 Core Processor
- 40 GB SSD Disk
- 2 TB Transfer

More pricing details at https://aws.amazon.com/lightsail/pricing/?opdp1=pricing

This service seems like it might be the best option for us. The space will probably be more than enough even at the lower end. The website specifically mentions that it is built to support web apps such as those that use NodeJS and the MEAN stack, so our MERN stack site would fit right in. It appears to cover pretty much everything we would need with AWS. More information at https://aws.amazon.com/lightsail/


Other potentially useful services:

- API Gateway - Publish, maintain, monitor, and secure APIs with 1,000,000 free requests/month (only free for first year)
- DynamoDB - NoSQL database service with up to 25GB free storage forever
- Lambda - compute service that allows code to be run only when needed (1,000,000 free requests/month forever)
- Route 53 - DNS service for managing records - monthly prices seem like they would be fairly low if the traffic to the - site stays low (much more expensive if you create a "traffic policy")
- DocumentDB (with MongoDB compatibility) - database service compatible with MongoDB - probably a bad option because the pricing seems to be very expensive, even on the low end
